### ISSUE TITLE
dotnet tool?

### ISSUE THREAD

**Issue by KirillOsenkov** [cklutz/LockCheck#10]
@cklutz once again thank you for creating this indispensable library!

Have you thought about publishing a dotnet global tool like lockcheck.exe such that you could run it from command line?

Long ago this used to be a console .exe project, but now it seems to be a library only?

**Comment by KirillOsenkov** [comment]
I pushed a branch in my fork if you're interested:
https://github.com/KirillOsenkov/LockCheck/tree/tool

**Comment by cklutz** [comment]
Oh yes, nice idea. Haven't thought about that. Go figure! :-)

I'm a bit busy for the next couple of weeks, but after that (or before, if possible at all), I'd gladly like to merge a PR. Thanks for the ownership offer. I accepted it in the hopes I can provide some value eventually.

**Comment by KirillOsenkov** [comment]
Here you go:
https://github.com/cklutz/LockCheck/pull/11

no rush!

**Comment by cklutz** [comment]
Finally :-) I merged it. Sorry for taking so long and thanks again! I will have to do some more work on this library in the next weeks (hopefully) the Linux tests are (still) broken and some other stuff...

**Comment by cklutz** [comment]
see above

**Comment by cklutz** [comment]
.
